# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yaf82zV0nQ6C4n3c_P8ws499n2NIxocQ
"""

# app.py file create in Colab
app_code = """
import streamlit as st
import pickle
import numpy as np

# Load the trained model
with open('heart_model.pkl', 'rb') as file:
    model = pickle.load(file)

st.title("❤️ Heart Disease Prediction App")
st.write("Fill in the details below to predict the likelihood of heart disease.")

# Input fields
age = st.number_input("Age", min_value=1, max_value=120, value=50)
resting_bp = st.number_input("Resting Blood Pressure (mm Hg)", min_value=50, max_value=250, value=120)
cholesterol = st.number_input("Cholesterol (mg/dl)", min_value=100, max_value=600, value=200)
max_hr = st.number_input("Max Heart Rate Achieved", min_value=60, max_value=220, value=150)
oldpeak = st.number_input("Oldpeak (ST depression)", min_value=0.0, max_value=10.0, value=1.0, step=0.1)
fasting_bs = st.number_input("Fasting Blood Sugar (>120 mg/dl: 1, else 0)", min_value=0, max_value=1, value=0)

if st.button("Predict"):
    features = np.array([age, resting_bp, cholesterol, max_hr, oldpeak, fasting_bs]).reshape(1, -1)
    prediction = model.predict(features)
    if prediction[0] == 1:
        st.error("Prediction: Heart Disease Likely ❤️")
    else:
        st.success("Prediction: Heart Disease Unlikely ✅")
"""

# Save as app.py
with open("app.py", "w") as f:
    f.write(app_code)

print("app.py created successfully!")